### ISSUE TITLE
Add-on Startup Failed

### ISSUE THREAD

**Issue by Pedram-Haxxor** [Petronian/dynamic-cards#6]
Hey. When I try to open Anki after installing the add-on, I get a startup failure. Here is the debug info:

```
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-13.5.2-arm64-arm-64bit

When loading Dynamic Cards:
Traceback (most recent call last):
  File "aqt.addons", line 250, in loadAddons
  File "/Users/****/Library/Application Support/Anki2/addons21/1902186394/__init__.py", line 299, in <module>
    dlg = WelcomeDialog(config.settings.show_modal)
  File "/Users/****/Library/Application Support/Anki2/addons21/1902186394/dialog.py", line 13, in __init__
    self.form.setupUi(self)
  File "/Users/****/Library/Application Support/Anki2/addons21/1902186394/ui/welcome.py", line 37, in setupUi
    sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
AttributeError: type object 'QSizePolicy' has no attribute 'Preferred'
```

**Comment by Petronian** [comment]
Must be a change to Qt/PyQt. I'll look into it. Thanks for debug info.

**Comment by Petronian** [comment]
Was an issue with QSizePolicy that they must have updated in newer versions of PyQt. Fixed in commit https://github.com/Petronian/dynamic-cards/commit/023c50a4102e16d15e3cf027ce1dac3dd0f354ff; re-open this issue if problems persist, but works fine on my machine.
